### ISSUE TITLE
Error Prototype/Implementation

### ISSUE THREAD

**Issue by daviandr** [OSU-CS361-W17/group1_project2#11]
It doesn't seem like there are a lot of errors to be had with the game. I see the user trying to place a ship where a ship is already placed, or firing at a position that has already be fired at. The easiest way to take care of this would probably be not making the UI do anything. Rather than displaying an error message, just not displaying anything on the screen and letting them figure out the action didn't take.  
Although, if our target is kids then they might not understand there was an error unless we tell them.  
Thoughts?

**Comment by jakevolkman** [comment]
There are still errors with the computer firing but other than that it works well. Closing this issue.
