### ISSUE TITLE
Paper Prototypes

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project2#4]
Everyone needs to provide a link to at least 3 paper prototypes for us to vote on. Please finish this by tomorrow's class so we can vote on them. The upload system seems broken, but I managed to get it working with links. Thanks.

**Comment by dmkato** [comment]
Hey @daviandr @nickywongdong, 
I think your prototypes are in private google docs, cause when I click them it says I need permission. Can you guys make those files public so we can vote?

**Comment by daviandr** [comment]
Try again

**Comment by jakevolkman** [comment]
Yeah I can view them

**Comment by dmkato** [comment]
Looks like we're done here!
