### ISSUE TITLE
ISSUES - Grading Policy & More

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project2#5]
I received comments on our performance. The comments have prompted me to make issues. If you have a question/need to communicate something to the group, please make an issue and ASSIGN someone to that issue, even if it is yourself. That is worth a significant portion of our grade.

Nicholas Nelson replied to me with the following information about our last project:

_Jacob,_

_Sorry for the delayed response. Let me go through each item you highlighted and provide further reasoning behind the grades._ 

_INVEST User Stories in GitHub Wiki:
Your group did well with the format of the user stories (Card, Conversation, Confirmation), but several of the stories were “As a developer, I want…”, which is not the correct usage of user stories. They are meant to motivate developers to add features based upon what a user would like to see in a software product. The 2 point deduction was for the format and subsequent feature mismatch between the 3 user stories that followed this “As a developer” pattern._

_Feature Request in GitHub Issues:
Your group actually had 5 issues (3 are still open, 2 have been closed). But the issues are not directly reflective of the features that needed to be implemented in order to complete the user stories your group outlined. Issue #11 (Placing Ships - Need Battleship Model) is a good issue, but the other issues were either lacking information for us to tie them to particular user stories or not directly related to completing any of the user stories._

_Greater than 90% test coverage in Java code:
A lot of groups struggled with this part of the assignment. Don’t feel discouraged about testing; CS362 is focused on testing and having at least some exposure to it will give you an advantage in that class._

_Extra Credit:
Since there are so many people in this CS361 course, the amount of emails and communications we receive is large. I suspect that Michael might have forgotten to enter the extra credit score, or forward your team’s email to me regarding it. If you could forward that email to me now, I will update the extra credit points for your group._

_Hope this helps.__

I managed to get some points back for us, but we really need to follow the rubric if we want to get points this time. Please read the rubric on Canvas.

**Comment by dmkato** [comment]
I'm just cleaning out the issues so our user story progress is clear
