### ISSUE TITLE
Merge Selected Designs into Paper Prototype

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project2#7]
As a group, create a new design prototype that merges the best ideas from the 3 selected designs. This prototype will be your group's framework for developing an updated Battleship game, so the quality of the sketch should be more complete than in previous designs. For this prototype, you will create three different states of the design:

Regular: This is how the interface will look when the user is in the middle of playing a game.
Blank: This is how the interface will look when the user starts a new game.
Error: This is how the interface will look when the user tries to do an illegal move.

**Comment by jakevolkman** [comment]
The results are in! 😍
No 1 is Andrew's 2nd prototype
No 2 is Daniel's 3rd 
No 3 is Nick's 2nd.
I don't know javascript and I barely know HTML or CSS, so I'd like to implement the Rick and Morty theme. If that's okay.

Here are the links to the winning designs:

https://docs.google.com/document/d/1I3MEpZGTy60ubuRFYdDk7p6LBcGIQNBUbVYP_rZs4HA/edit (The 2nd one)

http://i.imgur.com/h7JxgRN.png

https://drive.google.com/file/d/0B6rTPamRMJcLcmdoa2dNUDF2UWM/view

The instructions were to use these designs to form a final design.

Note that our grade will be determined by how we conform to the design we choose, and how well it is implemented.
Please be practical and reasonable when drawing it, to reduce the amount of work we have to do.

**Comment by jakevolkman** [comment]
Additionally, using a # followed by a number will link to the corresponding issue/pull request.
Example: #6

**Comment by daviandr** [comment]
So the first design is different from the last two. Are we going with one board on screen at a time, or two?

**Comment by dmkato** [comment]
Over and out
